sudo: required
services:
- docker
os:
- linux
env:
  global:
  #- DATABASE_USER={$DATABASE_USER}
  #- DATABASE_PASSWORD={$DATABASE_PASSWORD}
  #- DATABASE_URL={$DATABASE_URL}
  #- DATABASE_NAME={$DATABASE_NAME}
  - DOCKER_IMAGE_NAME="portofolio"
  - DOCKER_HUB_ORG="fabdulkarim"
before_install:
- openssl aes-256-cbc -K $encrypted_a905e3cd73ce_key -iv $encrypted_a905e3cd73ce_iv -in deploy.rsa.enc -out deploy.rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy.rsa
- ssh-add deploy.rsa
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
- sudo chmod +x deploy.sh
- sudo chmod 600 deploy.rsa
- sed -i -e 's|DBUSER|'"${DATABASE_USER}"'|g' .envdummy
- sed -i -e 's|DBPASS|'"${DATABASE_PASSWORD}"'|g' .envdummy
- sed -i -e 's|DBURL|'"${DATABASE_URL}"'|g' .envdummy
- sed -i -e 's|DBNAME|'"${DATABASE_NAME}"'|g' .envdummy
after_script:
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:latest
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy.rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR  'bash -s' < deploy.sh
#komen tes
#komen tes2
#komen tes re-install
#komen after re-login auth
